export const TEACHING_SUBJECTS = [
    'Mathematics',
    'Science',
    'Biology',
    'Physics',
    'Chemistry',
    'English',
    'Sinhala',
    'Tamil',
    'History',
    'Geography',
    'Commerce',
    'Economics',
    'Accounting',
    'ICT',
    'Art',
    'Music',
    'Physical Education',
    'Sports',
    'Literature',
    'General Knowledge',
];
