export const TEACHING_SUBJECTS = [
    'Mathematics',
    'Science',
    'Biology',
    'Physics',
    'Chemistry',
    'English',
    'Sinhala',
    'Tamil',
    'History',
    'Geography',
    'Commerce',
    'Economics',
    'Accounting',
    'ICT',
    'Art',
    'Music',
    'Physical Education',
    'Sports',
    'Literature',
    'General Knowledge',
];

export const CATEGORIES: SubjectCategory[] = [
    'All',
    'Primary',
    'Junior',
    'Ordinary Level',
    'Advanced Level',
    'Other',
];
