import { Teacher } from '@/types/teacher.types';

export const MOCK_TEACHERS: Teacher[] = [
    {
        id: 't-001',
        name: 'Kamal Perera',
        display_name: 'Mr. Kamal',
        initials: 'KP',
        nic: '901234567V',
        phone: '077-1234567',
        address: 'No. 45, Main Street, Colombo 05',
        subjects: ['Mathematics', 'Science'],
        color: '#3b82f6',
        status: 'active',
        classCount: 5,
        joinedDate: '2023-01-15',
        assignedClasses: [
            { id: 'c-001', name: 'Grade 10 Mathematics', grade: '10', medium: 'Sinhala', subject: 'Mathematics' },
            { id: 'c-002', name: 'Grade 11 Science', grade: '11', medium: 'Sinhala', subject: 'Science' },
            { id: 'c-003', name: 'Grade 10 Science', grade: '10', medium: 'Sinhala', subject: 'Science' },
            { id: 'c-004', name: 'Grade 9 Mathematics', grade: '9', medium: 'Sinhala', subject: 'Mathematics' },
            { id: 'c-005', name: 'Grade 11 Mathematics', grade: '11', medium: 'Sinhala', subject: 'Mathematics' },
        ],
        paymentInfo: {
            totalEarned: 125000,
            amountPaid: 100000,
            balanceDue: 25000,
            paymentHistory: [
                { id: 'p-001', date: '2025-01-15', amount: 50000, note: 'January advance' },
                { id: 'p-002', date: '2025-02-01', amount: 50000, note: 'February payment' },
            ],
        },
    },
    {
        id: 't-002',
        name: 'Nimali Fernando',
        display_name: 'Ms. Nimali',
        initials: 'NF',
        nic: '881234567V',
        phone: '077-2345678',
        address: 'No. 23, School Road, Kandy',
        subjects: ['English', 'Literature'],
        color: '#ec4899',
        status: 'active',
        classCount: 4,
        joinedDate: '2022-05-10',
        assignedClasses: [
            { id: 'c-006', name: 'Grade 10 English', grade: '10', medium: 'English', subject: 'English' },
            { id: 'c-007', name: 'Grade 11 English', grade: '11', medium: 'English', subject: 'English' },
            { id: 'c-008', name: 'Grade 12 English', grade: '12', medium: 'English', subject: 'English' },
            { id: 'c-009', name: 'Grade 13 Literature', grade: '13', medium: 'English', subject: 'Literature' },
        ],
        paymentInfo: {
            totalEarned: 98000,
            amountPaid: 98000,
            balanceDue: 0,
            paymentHistory: [
                { id: 'p-003', date: '2025-01-10', amount: 49000, note: 'January salary' },
                { id: 'p-004', date: '2025-02-05', amount: 49000, note: 'February salary' },
            ],
        },
    },
    {
        id: 't-003',
        name: 'Sunil Silva',
        display_name: 'Mr. Sunil',
        initials: 'SS',
        nic: '851234567V',
        phone: '077-3456789',
        address: 'No. 67, Lake View, Gampaha',
        subjects: ['Sinhala', 'History'],
        color: '#f59e0b',
        status: 'active',
        classCount: 6,
        joinedDate: '2021-03-20',
        assignedClasses: [
            { id: 'c-010', name: 'Grade 10 Sinhala', grade: '10', medium: 'Sinhala', subject: 'Sinhala' },
            { id: 'c-011', name: 'Grade 11 Sinhala', grade: '11', medium: 'Sinhala', subject: 'Sinhala' },
            { id: 'c-012', name: 'Grade 10 History', grade: '10', medium: 'Sinhala', subject: 'History' },
            { id: 'c-013', name: 'Grade 11 History', grade: '11', medium: 'Sinhala', subject: 'History' },
            { id: 'c-014', name: 'Grade 12 History', grade: '12', medium: 'Sinhala', subject: 'History' },
            { id: 'c-015', name: 'Grade 13 Sinhala', grade: '13', medium: 'Sinhala', subject: 'Sinhala' },
        ],
        paymentInfo: {
            totalEarned: 150000,
            amountPaid: 120000,
            balanceDue: 30000,
            paymentHistory: [
                { id: 'p-005', date: '2025-01-20', amount: 60000, note: 'Partial payment' },
                { id: 'p-006', date: '2025-02-10', amount: 60000, note: 'Monthly payment' },
            ],
        },
    },
    {
        id: 't-004',
        name: 'Priya Rathnayake',
        display_name: 'Mrs. Priya',
        initials: 'PR',
        nic: '921234567V',
        phone: '077-4567890',
        address: 'No. 89, Temple Road, Galle',
        subjects: ['Mathematics'],
        color: '#8b5cf6',
        status: 'active',
        classCount: 4,
        joinedDate: '2023-06-01',
        assignedClasses: [
            { id: 'c-016', name: 'Grade 6 Mathematics', grade: '6', medium: 'Sinhala', subject: 'Mathematics' },
            { id: 'c-017', name: 'Grade 7 Mathematics', grade: '7', medium: 'Sinhala', subject: 'Mathematics' },
            { id: 'c-018', name: 'Grade 8 Mathematics', grade: '8', medium: 'Sinhala', subject: 'Mathematics' },
            { id: 'c-019', name: 'Grade 9 Mathematics', grade: '9', medium: 'Sinhala', subject: 'Mathematics' },
        ],
        paymentInfo: {
            totalEarned: 80000,
            amountPaid: 80000,
            balanceDue: 0,
            paymentHistory: [
                { id: 'p-007', date: '2025-02-01', amount: 80000, note: 'Full payment' },
            ],
        },
    },
    {
        id: 't-005',
        name: 'Kasun Jayawardena',
        display_name: 'Mr. Kasun',
        initials: 'KJ',
        nic: '931234567V',
        phone: '077-5678901',
        address: 'No. 12, New Town, Anuradhapura',
        subjects: ['ICT', 'Mathematics'],
        color: '#06b6d4',
        status: 'active',
        classCount: 5,
        joinedDate: '2023-02-14',
        assignedClasses: [
            { id: 'c-020', name: 'Grade 10 ICT', grade: '10', medium: 'English', subject: 'ICT' },
            { id: 'c-021', name: 'Grade 11 ICT', grade: '11', medium: 'English', subject: 'ICT' },
            { id: 'c-022', name: 'Grade 12 ICT', grade: '12', medium: 'English', subject: 'ICT' },
            { id: 'c-023', name: 'Grade 13 ICT', grade: '13', medium: 'English', subject: 'ICT' },
            { id: 'c-024', name: 'Grade 10 Mathematics', grade: '10', medium: 'English', subject: 'Mathematics' },
        ],
        paymentInfo: {
            totalEarned: 110000,
            amountPaid: 80000,
            balanceDue: 30000,
            paymentHistory: [
                { id: 'p-008', date: '2025-01-15', amount: 40000, note: 'Advance' },
                { id: 'p-009', date: '2025-02-08', amount: 40000, note: 'Partial payment' },
            ],
        },
    },
    {
        id: 't-006',
        name: 'Deepika Wijesinghe',
        display_name: 'Ms. Deepika',
        initials: 'DW',
        nic: '941234567V',
        phone: '077-6789012',
        address: 'No. 34, Sea Street, Negombo',
        subjects: ['Science', 'Biology'],
        color: '#10b981',
        status: 'active',
        classCount: 4,
        joinedDate: '2022-09-05',
        assignedClasses: [
            { id: 'c-025', name: 'Grade 10 Science', grade: '10', medium: 'English', subject: 'Science' },
            { id: 'c-026', name: 'Grade 11 Science', grade: '11', medium: 'English', subject: 'Science' },
            { id: 'c-027', name: 'Grade 12 Biology', grade: '12', medium: 'English', subject: 'Biology' },
            { id: 'c-028', name: 'Grade 13 Biology', grade: '13', medium: 'English', subject: 'Biology' },
        ],
        paymentInfo: {
            totalEarned: 95000,
            amountPaid: 95000,
            balanceDue: 0,
            paymentHistory: [
                { id: 'p-010', date: '2025-02-01', amount: 95000, note: 'Full payment' },
            ],
        },
    },
    {
        id: 't-007',
        name: 'Ruwan Perera',
        display_name: 'Mr. Ruwan',
        initials: 'RP',
        nic: '891234567V',
        phone: '077-7890123',
        address: 'No. 56, Hill Street, Nuwara Eliya',
        subjects: ['Geography', 'Economics'],
        color: '#f97316',
        status: 'active',
        classCount: 4,
        joinedDate: '2021-08-12',
        assignedClasses: [
            { id: 'c-029', name: 'Grade 10 Geography', grade: '10', medium: 'Sinhala', subject: 'Geography' },
            { id: 'c-030', name: 'Grade 11 Geography', grade: '11', medium: 'Sinhala', subject: 'Geography' },
            { id: 'c-031', name: 'Grade 12 Economics', grade: '12', medium: 'Sinhala', subject: 'Economics' },
            { id: 'c-032', name: 'Grade 13 Economics', grade: '13', medium: 'Sinhala', subject: 'Economics' },
        ],
        paymentInfo: {
            totalEarned: 88000,
            amountPaid: 60000,
            balanceDue: 28000,
            paymentHistory: [
                { id: 'p-011', date: '2025-01-25', amount: 30000, note: 'Partial payment' },
                { id: 'p-012', date: '2025-02-12', amount: 30000, note: 'Monthly payment' },
            ],
        },
    },
    {
        id: 't-008',
        name: 'Nilanthi Karunaratne',
        display_name: 'Mrs. Nilanthi',
        initials: 'NK',
        nic: '871234567V',
        phone: '077-8901234',
        address: 'No. 78, Church Street, Jaffna',
        subjects: ['Tamil', 'History'],
        color: '#ef4444',
        status: 'inactive',
        classCount: 0,
        joinedDate: '2020-01-10',
        assignedClasses: [],
        paymentInfo: {
            totalEarned: 0,
            amountPaid: 0,
            balanceDue: 0,
            paymentHistory: [],
        },
    },
    {
        id: 't-009',
        name: 'Amal Wijesekara',
        display_name: 'Mr. Amal',
        initials: 'AW',
        nic: '911234567V',
        phone: '077-9012345',
        address: 'No. 90, Market Road, Kurunegala',
        subjects: ['Commerce', 'Accounting'],
        color: '#6366f1',
        status: 'active',
        classCount: 5,
        joinedDate: '2022-11-20',
        assignedClasses: [
            { id: 'c-033', name: 'Grade 10 Commerce', grade: '10', medium: 'Sinhala', subject: 'Commerce' },
            { id: 'c-034', name: 'Grade 11 Commerce', grade: '11', medium: 'Sinhala', subject: 'Commerce' },
            { id: 'c-035', name: 'Grade 12 Accounting', grade: '12', medium: 'Sinhala', subject: 'Accounting' },
            { id: 'c-036', name: 'Grade 13 Accounting', grade: '13', medium: 'Sinhala', subject: 'Accounting' },
            { id: 'c-037', name: 'Grade 12 Commerce', grade: '12', medium: 'Sinhala', subject: 'Commerce' },
        ],
        paymentInfo: {
            totalEarned: 105000,
            amountPaid: 105000,
            balanceDue: 0,
            paymentHistory: [
                { id: 'p-013', date: '2025-02-01', amount: 52500, note: 'January salary' },
                { id: 'p-014', date: '2025-02-06', amount: 52500, note: 'February salary' },
            ],
        },
    },
    {
        id: 't-010',
        name: 'Samantha Bandara',
        display_name: 'Ms. Samantha',
        initials: 'SB',
        nic: '951234567V',
        phone: '077-0123456',
        address: 'No. 21, Railway Ave, Ratnapura',
        subjects: ['Art', 'Music'],
        color: '#d946ef',
        status: 'active',
        classCount: 3,
        joinedDate: '2023-04-18',
        assignedClasses: [
            { id: 'c-038', name: 'Grade 6 Art', grade: '6', medium: 'Sinhala', subject: 'Art' },
            { id: 'c-039', name: 'Grade 7 Music', grade: '7', medium: 'Sinhala', subject: 'Music' },
            { id: 'c-040', name: 'Grade 8 Art', grade: '8', medium: 'Sinhala', subject: 'Art' },
        ],
        paymentInfo: {
            totalEarned: 45000,
            amountPaid: 30000,
            balanceDue: 15000,
            paymentHistory: [
                { id: 'p-015', date: '2025-02-10', amount: 30000, note: 'Advance payment' },
            ],
        },
    },
    {
        id: 't-011',
        name: 'Tharindu Liyanage',
        display_name: 'Mr. Tharindu',
        initials: 'TL',
        nic: '961234567V',
        phone: '077-1234568',
        address: 'No. 44, Green Road, Badulla',
        subjects: ['Physical Education', 'Sports'],
        color: '#84cc16',
        status: 'active',
        classCount: 6,
        joinedDate: '2023-07-01',
        assignedClasses: [
            { id: 'c-041', name: 'Grade 6 PE', grade: '6', medium: 'Sinhala', subject: 'Physical Education' },
            { id: 'c-042', name: 'Grade 7 PE', grade: '7', medium: 'Sinhala', subject: 'Physical Education' },
            { id: 'c-043', name: 'Grade 8 PE', grade: '8', medium: 'Sinhala', subject: 'Physical Education' },
            { id: 'c-044', name: 'Grade 9 PE', grade: '9', medium: 'Sinhala', subject: 'Physical Education' },
            { id: 'c-045', name: 'Grade 10 Sports', grade: '10', medium: 'Sinhala', subject: 'Sports' },
            { id: 'c-046', name: 'Grade 11 Sports', grade: '11', medium: 'Sinhala', subject: 'Sports' },
        ],
        paymentInfo: {
            totalEarned: 60000,
            amountPaid: 60000,
            balanceDue: 0,
            paymentHistory: [
                { id: 'p-016', date: '2025-02-01', amount: 60000, note: 'Full payment' },
            ],
        },
    },
    {
        id: 't-012',
        name: 'Chamari Mendis',
        display_name: 'Mrs. Chamari',
        initials: 'CM',
        nic: '881234568V',
        phone: '077-2345679',
        address: 'No. 67, Hospital Street, Matara',
        subjects: ['English', 'General Knowledge'],
        color: '#0ea5e9',
        status: 'active',
        classCount: 4,
        joinedDate: '2021-12-15',
        assignedClasses: [
            { id: 'c-047', name: 'Grade 6 English', grade: '6', medium: 'English', subject: 'English' },
            { id: 'c-048', name: 'Grade 7 English', grade: '7', medium: 'English', subject: 'English' },
            { id: 'c-049', name: 'Grade 8 English', grade: '8', medium: 'English', subject: 'English' },
            { id: 'c-050', name: 'Grade 9 GK', grade: '9', medium: 'English', subject: 'General Knowledge' },
        ],
        paymentInfo: {
            totalEarned: 75000,
            amountPaid: 50000,
            balanceDue: 25000,
            paymentHistory: [
                { id: 'p-017', date: '2025-01-20', amount: 25000, note: 'Partial payment' },
                { id: 'p-018', date: '2025-02-05', amount: 25000, note: 'Monthly installment' },
            ],
        },
    },
];

export const TEACHER_SUBJECTS = [
    'Mathematics',
    'Science',
    'Biology',
    'Physics',
    'Chemistry',
    'English',
    'Sinhala',
    'Tamil',
    'History',
    'Geography',
    'Commerce',
    'Economics',
    'Accounting',
    'ICT',
    'Art',
    'Music',
    'Physical Education',
    'Sports',
    'Literature',
    'General Knowledge',
];
